version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: library-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # API Integrator Service
  api_integrator:
    build:
      context: ./api_integrator
      dockerfile: Dockerfile
    container_name: library-api-integrator
    ports:
      - "${API_INTEGRATOR_PORT}:8080"
    environment:
      # Database Configuration
      DB_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      
      # API Key Configuration - using dot notation to match Spring property naming
      api.key.header.name: ${API_KEY_HEADER_NAME}
      api.key.admin: ${API_KEY_ADMIN}
      api.key.books: ${API_KEY_BOOKS}
      api.key.authors: ${API_KEY_AUTHORS}
      api.key.borrowed-books: ${API_KEY_BORROWED_BOOKS}
      
      # JPA Configuration
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL}
      SPRING_JPA_FORMAT_SQL: ${SPRING_JPA_FORMAT_SQL}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
    volumes:
      - ./api_integrator/logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - library-network
    restart: unless-stopped

  # Main API Service
  main_api:
    build:
      context: ./main_api
      dockerfile: Dockerfile
    container_name: library-main-api
    ports:
      - "${MAIN_API_PORT}:${SERVER_PORT}"
    environment:
      # Server Configuration
      SERVER_PORT: ${SERVER_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      
      # API Integrator Configuration
      API_INTEGRATOR_BASE_URL: ${API_INTEGRATOR_BASE_URL}
      API_INTEGRATOR_TIMEOUT: ${API_INTEGRATOR_TIMEOUT}
      
      # API Key Configuration
      API_KEY_HEADER_NAME: ${API_KEY_HEADER_NAME}
      API_KEY_ADMIN: ${API_KEY_ADMIN}
      API_KEY_BOOKS: ${API_KEY_BOOKS}
      API_KEY_AUTHORS: ${API_KEY_AUTHORS}
      API_KEY_BORROWED_BOOKS: ${API_KEY_BORROWED_BOOKS}
      
      # Security Configuration - Allow frontend container and localhost
      ALLOWED_IPS: ${ALLOWED_IPS}
      FRONTEND_IP: ${FRONTEND_IP}
    volumes:
      - ./main_api/logs:/app/logs
    depends_on:
      - api_integrator
    networks:
      - library-network
    restart: unless-stopped

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: library-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - main_api
    networks:
      - library-network

volumes:
  postgres_data:

networks:
  library-network:
    driver: bridge 