spring:
  application:
    name: library-management
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Disable second-level cache
        cache:
          use_second_level_cache: false
          use_query_cache: false
  # Disable Spring Boot's cache auto-configuration
  cache:
    type: none
  datasource:
    url: jdbc:postgresql://postgres:5432/librarydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # H2 Database for development (comment out PostgreSQL above to use H2)
  #datasource:
  #  url: jdbc:h2:mem:testdb
  #  driver-class-name: org.h2.Driver
  #  username: sa
  #  password: password
  #h2:
  #  console:
  #    enabled: true

server:
  port: 8080
  servlet:
    context-path: /api

# CORS configuration
cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"

# Logging
logging:
  level:
    com.library: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# SpringDoc OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    
# Pagination defaults
pagination:
  default-page-size: 10
  max-page-size: 100 