server:
  port: ${SERVER_PORT:8090}
  servlet:
    context-path: /api

spring:
  application:
    name: library-main-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# API Integrator Configuration
api-integrator:
  base-url: ${API_INTEGRATOR_BASE_URL:http://api_integrator:8080}
  timeout: ${API_INTEGRATOR_TIMEOUT:5000}
  
  # API Key Configuration
  api-keys:
    admin: ${API_KEY_ADMIN:admin-api-key-123}
    books: ${API_KEY_BOOKS:books-api-key-456}
    authors: ${API_KEY_AUTHORS:authors-api-key-789}
    borrowed-books: ${API_KEY_BORROWED_BOOKS:borrowed-books-api-key-101}
  
  # API Key Header Name
  api-key-header: ${API_KEY_HEADER_NAME:X-API-KEY}

# Security Configuration
security:
  allowed-ips: ${ALLOWED_IPS:127.0.0.1,::1,192.168.1.1,10.0.0.1}
  # Frontend client IP address
  frontend-ip: ${FRONTEND_IP:127.0.0.1}

# Logging Configuration
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.library.main_api: ${LOGGING_LEVEL_APP:DEBUG}
    org.springframework.web: ${LOGGING_LEVEL_WEB:INFO}
    org.springframework.security: ${LOGGING_LEVEL_SECURITY:INFO}

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      apiIntegrator:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
  retry:
    instances:
      apiIntegrator:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.util.concurrent.TimeoutException

# API Documentation
springdoc:
  api-docs:
    path: /docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
  show-actuator: true 