server:
  port: ${SERVER_PORT:8090}
  servlet:
    context-path: /api

spring:
  application:
    name: library-main-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# API Integrator Configuration
api:
  integrator:
    base:
      url: ${API_INTEGRATOR_BASE_URL:http://localhost:8080}
    timeout: ${API_INTEGRATOR_TIMEOUT:5000}
  key:
    header:
      name: ${API_KEY_HEADER_NAME:X-API-KEY}
    admin: ${API_KEY_ADMIN:admin-api-key-123}
    books: ${API_KEY_BOOKS:books-api-key-456}
    authors: ${API_KEY_AUTHORS:authors-api-key-789}
    borrowed-books: ${API_KEY_BORROWED_BOOKS:borrowed-books-api-key-101}

# Logging Configuration
logging:
  level:
    root: INFO
    com.library: DEBUG
    com.library.main_api.service: TRACE
    org.springframework.web: INFO
    org.springframework.web.client.RestTemplate: DEBUG
  file:
    name: logs/main-api.log
    max-size: 10MB
    max-history: 10

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  show-actuator: true

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    com.library: DEBUG
    com.library.main_api.service: TRACE
    org.springframework.web: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.library: INFO
    org.springframework.web: WARN 